### ISSUE TITLE
Exercise 25 error

### ISSUE THREAD

**Issue by Extremesarova** [vopani/datatableton#11]
**Describe Error**
"Select the element in the 4th row and 2nd column in `data` and assign it to `value_1`..."
Provided solution:
`value_1 = data[4, 3]`

**Exercise / Set**
Exercise 25 / Set 3

**Suggested Fix**
Shouldn't it be like `value_1 = data[3, 1]` or I'm missing something? 
4th row considering numeration from 0 -> 3
2nd column considering numeration from 0 -> 1

**Comment by vopani** [comment]
Thank you for reporting this. You are right.
It is now fixed with `data[3, 1]`
