### ISSUE TITLE
Exercise 45 error

### ISSUE THREAD

**Issue by Extremesarova** [vopani/datatableton#12]
**Describe Error**
It is asked in the task to find the mode for several columns. 
The right answer is:
alcohol | proline
12.37 | 520.0
13.05 | 680.0
Because the mode is not necessarily unique to a given discrete distribution, the probability mass function may take the same maximum value at several points.
In this case, alcohol values are repeated 6 times and proline values are repeated 5 times.

**Exercise / Set**
Exercise 45 / Set 5

**Suggested Fix**
I don't know - maybe you can specify in the task that only the first value should be returned or the `mode` function can be improved so it will return multiple values.

**Comment by vopani** [comment]
Thank you for sharing this.

Having the `mode` function output multiple values in case of a tie is a core library functionality and better suited for the official [datatable repository](https://github.com/h2oai/datatable).

For the sake of removing the ambiguity here, I've updated the exercise to use columns that have a unique mode value.
